Install Libraries

In [1]:
import pandas as pd

Load data

In [3]:
labels = pd.read_csv("labels.csv")
df = pd.read_csv("all_analysis_data.csv")
df["API_Labels"] = labels
df.head()

                                           API_Calls API_Labels
0  ldrloaddll ldrgetprocedureaddress ldrloaddll l...     Trojan
1  getsystemtimeasfiletime ntallocatevirtualmemor...     Trojan
2  ldrgetdllhandle ldrgetprocedureaddress getsyst...   Backdoor
3  ldrloaddll ldrgetprocedureaddress ldrloaddll l...   Backdoor
4  ldrloaddll ldrgetprocedureaddress ldrgetproced...     Trojan

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7107 entries, 0 to 7106
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   API_Calls   7107 non-null   str
 1   API_Labels  7107 non-null   str
dtypes: str(2)
memory usage: 111.2 KB

In [7]:
df.describe()

                                                API_Calls API_Labels
count                                                7107       7107
unique                                               6518          8
top     ntallocatevirtualmemory ntfreevirtualmemory nt...     Trojan
freq                                                   25       1001